CREATE TABLE IF NOT EXISTS personal_ubicacion (
    "Apellido Nombres" TEXT,
    "Sector" TEXT,
    "Establecimiento" TEXT,
    "Ubicación" TEXT
);

INSERT INTO personal_ubicacion VALUES ('ACEBAL CLAUDIO SAMUEL', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ACUÑA NICOLAS JOSE', 'Contaduria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ALVAREZ FEDERICO EZEQUIEL', 'Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ALVAREZ LUCIANO RAUL', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('AMASINO GUILLERMO ARIEL', 'Serv. Complementario-T.E', 'Planta Operativa', 'Frente al Bloque II');
INSERT INTO personal_ubicacion VALUES ('ANDINA EZEQUIEL LEANDRO', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ANTUNEZ ARIEL ANTONIO', 'Jefe de Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ANTUNEZ MAURICIO ALBERTO', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ARANCIBIA FRANCO DAVID', 'Almacen', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ARANCIBIA SEBASTIAN DANIEL', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ARECHABALA MAXIMILIANO JOSE', 'Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('BAILES FEDERICO DANIEL', 'I y C', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('BRAÑA NESTOR FABIAN', 'Contaduría', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CABARCOS LODI LEANDRO', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CABRAL VICTORIANO HUGO', 'Serv. Complementario-T.E', 'Planta Operativa', 'Frente al Bloque II');
INSERT INTO personal_ubicacion VALUES ('CALLES NICOLAS', 'Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CALVENTO LEANDRO AGUSTIN', 'Serv. Complementario T-H', 'Planta Operativa', 'Frente al Bloque II');
INSERT INTO personal_ubicacion VALUES ('CANZIANI LUCIA MARIA', 'Oficina de Personal', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('CANZIANI MARIA JULIA', 'Contaduría', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CEJAS CARLOS MATIAS', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CEJAS GRACIELA LUCIANA', 'Facturado', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CHIACCHIO, RODOLFO EZEQUIEL', 'Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CONFORTI ESTEBAN IGNACIO', 'Asist. Técnica', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('CONQUEIRA JOSE MARIA', 'Tablerista', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('DALCEGGIO CESAR MAURO', 'Jefe de Mantenimiento', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('De BASTOS ALEJANDRA NOEMI', 'Compras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('DE BASTOS CARLOS MARIANO', 'Alumbrado Público', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('DE BASTOS FEDERICO JOSÉ MARÍA', 'Alumbrado Público', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('DE BASTOS MARIA JOSE', 'Caja', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('DE LA VEGA LUCAS ROBERTO', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('DEL GIORGIO NICOLAS MARTIN', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('DI GIANO NICOLAS', 'Tablerista', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('DI GIANO TOMAS', 'Cobranzas (cuadrilla)', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ECHANDI MARCELO EZEQUIEL', 'Guardia Reclamos 1', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('EIZMENDI JOSE ORLANDO', 'Parques y Paseos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ESTAYNO GUILLERMO JULIAN', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ESTAYNO JUAN IGNACIO', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ESTAYNO MARIANO JOSE', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ESTRADE MARTIN EDUARDO', 'Tablerista', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('FERNANDEZ AGUSTIN', 'Jefe Compras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('FERNANDEZ MANUEL', 'Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('FERNANDEZ MARCELO EMILIANO', 'Jefe de Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('FERRARI PEDRO MANUEL', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('FERRERAS EZEQUIEL', 'Caja', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('FRUMBOLI MARIA SUSANA', 'Mesa de Entrada', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GAIADA GASTON EZEQUIEL', 'Facturado', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GAIADA MARIA BELEN', 'Facturado', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GAIADA SERGIO FACUNDO', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GALLARDO MARCOS MIGUEL', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GALLARDO VIRGINIA ESTEFANIA', 'Personal', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('GALLEGO MARIA LUCIA', 'Obras', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('GARCIA ALESSI MILAGROS', 'Pagos', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GARCIA JUAN', 'Obras', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('GATICA JOSE MARIA', 'I y C', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GES BERNARDO', 'Asist. Técnica', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GIRELLI RODOLFO RAFAEL', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GOENAGA BARROSO MARIA GABRIELA', 'Cobranzas', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GOENAGA MARCOS JAVIER', 'I y C', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GOMEZ JAVIER', 'Tablerista', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('GOMEZ YANINA', 'Mesa de Entrada', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GONZALEZ CLAVERIE RICARDO', 'Facturado (cuadrilla)', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GONZALEZ MARCOS OSCAR', 'Jefe de Serv. Complementario', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GONZALEZ MARTIN DANIEL', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GRECO GUILLERMO DAMIAN', 'Adjunto Gerencia Técnica', 'Planta Operativa', 'Bloque II Primer Piso');
INSERT INTO personal_ubicacion VALUES ('GRONDONA JOAQUIN', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GRONDONA LUCIANO LUIS', 'Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GRONDONA RAUL DARIO', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('GUILLEN MARIA BELEN', 'Mesa de Entrada', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('HERNADEZ LUIS NAHUEL', 'Almacenes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('HERNANDEZ LUIS MARIA', 'Jefe de Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('HERNANDO Exequiel', 'I y C', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('JUAREZ MATIAS OMAR', 'Parques y Paseos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('KEEGAN ALEJANDRO LUIS', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LARA ANALIA', 'Compras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('LARA JULIAN', 'Obras', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('LAVAYEN JORGE SEBASTIAN', 'Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LEGUIZAMON GERARDO MARIO', 'Facturado (cuadrilla)', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LESCANO MARIA CECILIA', 'Encargada de Cobranza', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LEVAGGI JORGE RICARDO', 'Jefe de Facturado', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LOPEZ GONZALO EZEQUIEL', 'Cobranzas (cuadrilla)', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LOPEZ SERGIO HERNAN', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('LOPEZ VANESA LILIANA', 'Mesa de Entrada', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MALLO MILAGROS', 'Encargada de Pago', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MANOLIO ANTONIO ALBERTO', 'Adjunto Gerencia Técnica', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('MARBAN JORGELINA BELEN', 'Asist. Técnica', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MARBAN NICOLAS', 'Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MENDEZ MATIAS', 'Parques y Paseos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MIRAMONT MATIAS ENRIQUE', 'Jefe de I y C', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MONTENEGRO MARTIN', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('MORA VICTOR JAVIER', 'Calidad de Servicio', 'Planta Operativa', 'Bloque II Primer Piso');
INSERT INTO personal_ubicacion VALUES ('NOTTI JUAN FRANCISCO', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('NUÑEZ GONZALO SEBASTIAN', 'Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('OTERO DANIEL ANDRES', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('OTERO MATIAS EZEQUIEL', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('PATERNOSTER CRISTIAN EMANUEL', 'Tablerista', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('PATERNOSTER LEANDRO', 'Serv. Complementario T-H', 'Planta Operativa', 'Frente al Bloque II');
INSERT INTO personal_ubicacion VALUES ('PEREZ DIEGO JOSE', 'Jefe de Almacen', 'Planta Operativa', 'Bloque II Primer Piso');
INSERT INTO personal_ubicacion VALUES ('PEROTTI MATIAS NICOLAS', 'Conexiones', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('PERSSON MAURICIO ALEJANDR', 'Jefe de Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('PIEDRA DAMIAN ALEJANDRO', 'Calidad de Servicio', 'Planta Operativa', 'Bloque II Primer Piso');
INSERT INTO personal_ubicacion VALUES ('PUGGIONI LUCAS', 'Serv. Complementario-T.E', 'Planta Operativa', 'Frente al Bloque II');
INSERT INTO personal_ubicacion VALUES ('RECA RAUL JESUS', 'Jefe de Distribución', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('RECLUSA MARTIN', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('RECLUSA PABLO', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('REZOLA IGNACIO ANDRES', 'I y C', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('RIELO DAVID', 'Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('RISSO FRANCISCO', 'Facturado', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('RISSO JUAN CARLOS', 'Oficina de Personal', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('RODRIGUEZ NICOLAS', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('RODRIGUEZ PABLO DANIEL', 'Facturado', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ROSSI FRANCO', 'Parques y Paseos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SAAB GUILLERMO DARIO', 'Gerente Técnico', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('SABIO MARIA LAURA', 'Adjunto Gerencia Administrativo y Financiero', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SCHOSTERICH FERNANDO', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SCHOSTERICH GORZ ANTONIO', 'Cobranzas (cuadrilla)', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SCHOSTERICH MERCEDES', 'Mesa de Entrada', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SOLVER ALEJANDRO YAEL', 'Cobranzas (cuadrilla)', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SPELOZZO TAPIA EMANUEL', 'Obras', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('STAMPONE FABRICIO ALBERTO', 'Adjunto Gerencia Técnica', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('STORTI JOAQUIN', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('SUAREZ MAXIMILIANO', 'Laboratorio', 'Planta Operativa', 'Bloque I Planta Baja');
INSERT INTO personal_ubicacion VALUES ('TERMINIELLO JUAN CARLOS', 'Almacenes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('TOMAS RIMOLI HECTOR MATIAS', 'IyC', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('TRACANA MATIAS EZEQUIEL', 'Obras', 'Planta Operativa', 'Bloque I Primer Piso');
INSERT INTO personal_ubicacion VALUES ('TREVOLAZAVALA MATIAS ROBERTO', 'Serv. Complementario T-H', 'Planta Operativa', 'Frente al Bloque II');
INSERT INTO personal_ubicacion VALUES ('TRONCOSO EMILIANO EZEQUIEL', 'Serv. Complementario-T.T', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('TRONCOSO LIONEL', 'Subestaciones', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('TRONCOSO MATIAS', 'Almacenes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('UGARTE ENRIQUE ESTEBAN', 'Automotores', 'Planta Operativa', 'Bloque II Primer Piso');
INSERT INTO personal_ubicacion VALUES ('URRACO DIEGO MARTIN', 'Tablerista', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('VALLE WALTER FABIAN', 'Gerente Administrativo, Financiero y Laboral', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('VALLEJOS ELIANA ANDREA', 'Secretaria Directorio', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('VARGAS GUILLERMINA LORENA', 'Facturación', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('VARGAS GUTIERREZ LEONARDO JAVIER', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('VERON JUAN DIEGO', 'Guardia Reclamos 1', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('VERON MATIAS RUBEN', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('VERON RODRIGO ALDO', 'Redes', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('VOUILLOZ RICARDO MARTIN', 'Guardia Reclamos', 'Planta Operativa', 'Bloque II Planta Baja');
INSERT INTO personal_ubicacion VALUES ('ZAMPATTI MARIANO GABRIEL', 'Adjunto a Gerencia Laboral', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Acosta Damian Agustin', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Alvarez Lucas Daniel', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Andreoli Gustavo Alberto', 'Enfermeria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Ayala Lucas Benjamin', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Blanco Carlos Damian', 'Enfermeria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Cappelutti Sergio Osvaldo', 'Enfermeria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Caruso Nahuel Nicolas', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Chiachio Milagros', 'Usittel', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Corro Joana Antonela', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('D Annunzio Adrian', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Di Marco Ramiro', 'Administración', 'Edificio Administrativo', 'Segundo Piso');
INSERT INTO personal_ubicacion VALUES ('Diaz Delfino Manuel', 'Gerencia', 'Edificio Administrativo', 'Segundo Piso');
INSERT INTO personal_ubicacion VALUES ('Dobal Esteban David', 'Traslados', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Espain Cirilo Francisco', 'Energía Renovables y Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Guglielminotti Mauricio Omar', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Herrera Marcos Gaston', 'Enfermeria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Lucero Diego Emanuel', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Mehats Natalia Belén', 'Administración', 'Edificio Administrativo', 'Segundo Piso');
INSERT INTO personal_ubicacion VALUES ('Molina Gaton Leandro', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Naturan Gonzalo', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Naturan Santiago Daniel', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Patron Julio Alejandro', 'Traslados', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Pecelis Gustavo Cesar', 'Médico', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Pelizza Agustín', 'Gerencia', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Reyes Monica Estela', 'Enfermeria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Riggieri Guillermo Oscar', 'Traslados', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Romano Monica Adriana', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Suarez Marcelo Javier', 'Enfermeria', 'Edificio Administrativo', 'Planta Baja');
INSERT INTO personal_ubicacion VALUES ('Tolosa Nestor Julio', 'Obras', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Vacarezza, Juan Manuel', 'Administración', 'Edificio Administrativo', 'Primer Piso');
INSERT INTO personal_ubicacion VALUES ('Vazquez Martin Luis', 'Administración', 'Edificio Administrativo', 'Segundo Piso');
INSERT INTO personal_ubicacion VALUES ('Vinsennau Juan Ignacio', 'Obras', 'Edificio Administrativo', 'Primer Piso');
